# Generated by Django 4.1.7 on 2023-04-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_listbook_type_list_listbookbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listbookbook',
            old_name='book_id',
            new_name='book',
        ),
    ]
