# Generated by Django 4.1.7 on 2023-04-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_book_id_listbookbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='writter',
            field=models.BooleanField(default=False),
        ),
    ]
