# Generated by Django 4.1.7 on 2023-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userlibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupreaders',
            name='image',
            field=models.ImageField(blank=True, upload_to='group_images'),
        ),
    ]
