# Generated by Django 4.1.7 on 2023-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_resenya_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='stars',
            field=models.IntegerField(verbose_name=range(1, 5)),
        ),
    ]
