# Generated by Django 4.1.7 on 2023-04-30 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_resenya_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenya',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
