# Generated by Django 4.1.7 on 2023-05-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_bookssection_bookssectionbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookssection',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
