# Generated by Django 4.1.7 on 2023-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_bookssection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookssection',
            name='colorHex',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
