# Generated by Django 4.1.7 on 2023-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_bookssection_colorhex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookssection',
            name='colorHex',
        ),
        migrations.AddField(
            model_name='bookssection',
            name='color',
            field=models.CharField(choices=[('verde', 'Verde'), ('rojo', 'Rojo'), ('azul', 'Azul'), ('amarillo', 'Amarillo'), ('morado', 'Morado')], default='verde', max_length=10),
        ),
    ]
