# Generated by Django 4.1.7 on 2023-05-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
